
// This file has been generated by the GUI designer. Do not modify.
namespace Vodovoz.Views.Cash
{
	public partial class CashIncomeView
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Button buttonSave;

		private global::Gtk.Button buttonCancel;

		private global::Gamma.GtkWidgets.yButton buttonPrint;

		private global::Gtk.HBox hboxSubdivision;

		private global::Gamma.GtkWidgets.yLabel labelCashSubdivision;

		private global::Gamma.Widgets.ySpecComboBox comboCashSubdivision;

		private global::Gtk.Table table1;

		private global::Gamma.GtkWidgets.yCheckButton checkNoClose;

		private global::Gamma.Widgets.ySpecComboBox comboExpenseCategory;

		private global::Gamma.Widgets.ySpecComboBox comboIncomeCategory;

		private global::QS.Widgets.GtkUI.EntityViewModelEntry entryClient;

		private global::QS.Widgets.GtkUI.EntityViewModelEntry entryEmployee;

		private global::Gamma.Widgets.yEnumComboBox enumcomboOperation;

		private global::Gtk.HBox hbox7;

		private global::Gamma.GtkWidgets.ySpinButton yspinMoney;

		private global::QSProjectsLib.CurrencyLabel currencylabel1;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.Label label5;

		private global::Gamma.GtkWidgets.yLabel labelClientTitle;

		private global::Gtk.Label labelEmploeey;

		private global::Gtk.Label labelExpenseTitle;

		private global::Gtk.Label labelIncomeTitle;

		private global::Gamma.GtkWidgets.yLabel labelRouteList;

		private global::QS.Widgets.GtkUI.DatePicker ydateDocument;

		private global::QS.Widgets.GtkUI.RepresentationEntry yEntryRouteList;

		private global::Gamma.GtkWidgets.yLabel ylabelCashier;

		private global::Gtk.VBox vboxDebts;

		private global::Gtk.Label labelTableTitle;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gamma.GtkWidgets.yTreeView ytreeviewDebts;

		private global::Gtk.Label label6;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gamma.GtkWidgets.yTextView ytextviewDescription;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Vodovoz.Views.Cash.CashIncomeView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Vodovoz.Views.Cash.CashIncomeView";
			// Container child Vodovoz.Views.Cash.CashIncomeView.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonSave = new global::Gtk.Button();
			this.buttonSave.CanFocus = true;
			this.buttonSave.Name = "buttonSave";
			this.buttonSave.UseUnderline = true;
			this.buttonSave.Label = global::Mono.Unix.Catalog.GetString("Сохранить");
			global::Gtk.Image w1 = new global::Gtk.Image();
			w1.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-save", global::Gtk.IconSize.Menu);
			this.buttonSave.Image = w1;
			this.hbox2.Add(this.buttonSave);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.buttonSave]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString("Отменить");
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-revert-to-saved", global::Gtk.IconSize.Menu);
			this.buttonCancel.Image = w3;
			this.hbox2.Add(this.buttonCancel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.buttonCancel]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonPrint = new global::Gamma.GtkWidgets.yButton();
			this.buttonPrint.CanFocus = true;
			this.buttonPrint.Name = "buttonPrint";
			this.buttonPrint.UseUnderline = true;
			this.buttonPrint.Label = global::Mono.Unix.Catalog.GetString("Печать");
			global::Gtk.Image w5 = new global::Gtk.Image();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-print", global::Gtk.IconSize.Menu);
			this.buttonPrint.Image = w5;
			this.hbox2.Add(this.buttonPrint);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.buttonPrint]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.hboxSubdivision = new global::Gtk.HBox();
			this.hboxSubdivision.Name = "hboxSubdivision";
			this.hboxSubdivision.Spacing = 6;
			// Container child hboxSubdivision.Gtk.Box+BoxChild
			this.labelCashSubdivision = new global::Gamma.GtkWidgets.yLabel();
			this.labelCashSubdivision.Name = "labelCashSubdivision";
			this.labelCashSubdivision.Xalign = 1F;
			this.labelCashSubdivision.LabelProp = global::Mono.Unix.Catalog.GetString("Касса:");
			this.hboxSubdivision.Add(this.labelCashSubdivision);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hboxSubdivision[this.labelCashSubdivision]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hboxSubdivision.Gtk.Box+BoxChild
			this.comboCashSubdivision = new global::Gamma.Widgets.ySpecComboBox();
			this.comboCashSubdivision.Name = "comboCashSubdivision";
			this.comboCashSubdivision.AddIfNotExist = false;
			this.comboCashSubdivision.DefaultFirst = false;
			this.comboCashSubdivision.ShowSpecialStateAll = false;
			this.comboCashSubdivision.ShowSpecialStateNot = true;
			this.hboxSubdivision.Add(this.comboCashSubdivision);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hboxSubdivision[this.comboCashSubdivision]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.hbox2.Add(this.hboxSubdivision);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.hboxSubdivision]));
			w9.Position = 3;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(8)), ((uint)(4)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.checkNoClose = new global::Gamma.GtkWidgets.yCheckButton();
			this.checkNoClose.CanFocus = true;
			this.checkNoClose.Name = "checkNoClose";
			this.checkNoClose.Label = global::Mono.Unix.Catalog.GetString("Частичный возврат");
			this.checkNoClose.DrawIndicator = true;
			this.checkNoClose.UseUnderline = true;
			this.table1.Add(this.checkNoClose);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.checkNoClose]));
			w11.TopAttach = ((uint)(6));
			w11.BottomAttach = ((uint)(7));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.comboExpenseCategory = new global::Gamma.Widgets.ySpecComboBox();
			this.comboExpenseCategory.Name = "comboExpenseCategory";
			this.comboExpenseCategory.AddIfNotExist = false;
			this.comboExpenseCategory.DefaultFirst = false;
			this.comboExpenseCategory.ShowSpecialStateAll = false;
			this.comboExpenseCategory.ShowSpecialStateNot = true;
			this.table1.Add(this.comboExpenseCategory);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.comboExpenseCategory]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.comboIncomeCategory = new global::Gamma.Widgets.ySpecComboBox();
			this.comboIncomeCategory.Name = "comboIncomeCategory";
			this.comboIncomeCategory.AddIfNotExist = false;
			this.comboIncomeCategory.DefaultFirst = false;
			this.comboIncomeCategory.ShowSpecialStateAll = false;
			this.comboIncomeCategory.ShowSpecialStateNot = true;
			this.table1.Add(this.comboIncomeCategory);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.comboIncomeCategory]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryClient = new global::QS.Widgets.GtkUI.EntityViewModelEntry();
			this.entryClient.Events = ((global::Gdk.EventMask)(256));
			this.entryClient.Name = "entryClient";
			this.entryClient.CanEditReference = false;
			this.table1.Add(this.entryClient);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.entryClient]));
			w14.TopAttach = ((uint)(4));
			w14.BottomAttach = ((uint)(5));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryEmployee = new global::QS.Widgets.GtkUI.EntityViewModelEntry();
			this.entryEmployee.Events = ((global::Gdk.EventMask)(256));
			this.entryEmployee.Name = "entryEmployee";
			this.entryEmployee.CanEditReference = false;
			this.table1.Add(this.entryEmployee);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.entryEmployee]));
			w15.TopAttach = ((uint)(5));
			w15.BottomAttach = ((uint)(6));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.enumcomboOperation = new global::Gamma.Widgets.yEnumComboBox();
			this.enumcomboOperation.Name = "enumcomboOperation";
			this.enumcomboOperation.ShowSpecialStateAll = false;
			this.enumcomboOperation.ShowSpecialStateNot = false;
			this.enumcomboOperation.UseShortTitle = false;
			this.enumcomboOperation.DefaultFirst = false;
			this.table1.Add(this.enumcomboOperation);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1[this.enumcomboOperation]));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.yspinMoney = new global::Gamma.GtkWidgets.ySpinButton(0D, 2147483647D, 100D);
			this.yspinMoney.CanDefault = true;
			this.yspinMoney.CanFocus = true;
			this.yspinMoney.Name = "yspinMoney";
			this.yspinMoney.Adjustment.PageIncrement = 1000D;
			this.yspinMoney.ClimbRate = 1D;
			this.yspinMoney.Digits = ((uint)(2));
			this.yspinMoney.Numeric = true;
			this.yspinMoney.ValueAsDecimal = 0m;
			this.yspinMoney.ValueAsInt = 0;
			this.hbox7.Add(this.yspinMoney);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.yspinMoney]));
			w17.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.currencylabel1 = new global::QSProjectsLib.CurrencyLabel();
			this.currencylabel1.Name = "currencylabel1";
			this.currencylabel1.LabelProp = global::Mono.Unix.Catalog.GetString("currencylabel1");
			this.hbox7.Add(this.currencylabel1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.currencylabel1]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.table1.Add(this.hbox7);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1[this.hbox7]));
			w19.TopAttach = ((uint)(7));
			w19.BottomAttach = ((uint)(8));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Дата:");
			this.table1.Add(this.label1);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1[this.label1]));
			w20.TopAttach = ((uint)(1));
			w20.BottomAttach = ((uint)(2));
			w20.LeftAttach = ((uint)(2));
			w20.RightAttach = ((uint)(3));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Кассир:");
			this.table1.Add(this.label2);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1[this.label2]));
			w21.LeftAttach = ((uint)(2));
			w21.RightAttach = ((uint)(3));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.Xalign = 1F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Тип операции:");
			this.table1.Add(this.label3);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1[this.label3]));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.Xalign = 1F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Сумма:");
			this.table1.Add(this.label5);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1[this.label5]));
			w23.TopAttach = ((uint)(7));
			w23.BottomAttach = ((uint)(8));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelClientTitle = new global::Gamma.GtkWidgets.yLabel();
			this.labelClientTitle.Name = "labelClientTitle";
			this.labelClientTitle.Xalign = 1F;
			this.labelClientTitle.LabelProp = global::Mono.Unix.Catalog.GetString("Клиент:");
			this.table1.Add(this.labelClientTitle);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1[this.labelClientTitle]));
			w24.TopAttach = ((uint)(4));
			w24.BottomAttach = ((uint)(5));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelEmploeey = new global::Gtk.Label();
			this.labelEmploeey.Name = "labelEmploeey";
			this.labelEmploeey.Xalign = 1F;
			this.labelEmploeey.LabelProp = global::Mono.Unix.Catalog.GetString("Сотрудник:");
			this.table1.Add(this.labelEmploeey);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1[this.labelEmploeey]));
			w25.TopAttach = ((uint)(5));
			w25.BottomAttach = ((uint)(6));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelExpenseTitle = new global::Gtk.Label();
			this.labelExpenseTitle.Name = "labelExpenseTitle";
			this.labelExpenseTitle.Xalign = 1F;
			this.labelExpenseTitle.LabelProp = global::Mono.Unix.Catalog.GetString("Статья расхода:");
			this.table1.Add(this.labelExpenseTitle);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1[this.labelExpenseTitle]));
			w26.TopAttach = ((uint)(2));
			w26.BottomAttach = ((uint)(3));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelIncomeTitle = new global::Gtk.Label();
			this.labelIncomeTitle.Name = "labelIncomeTitle";
			this.labelIncomeTitle.Xalign = 1F;
			this.labelIncomeTitle.LabelProp = global::Mono.Unix.Catalog.GetString("Статья дохода:");
			this.table1.Add(this.labelIncomeTitle);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1[this.labelIncomeTitle]));
			w27.TopAttach = ((uint)(1));
			w27.BottomAttach = ((uint)(2));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelRouteList = new global::Gamma.GtkWidgets.yLabel();
			this.labelRouteList.Name = "labelRouteList";
			this.labelRouteList.Xalign = 1F;
			this.labelRouteList.LabelProp = global::Mono.Unix.Catalog.GetString("Маршрутный лист:");
			this.table1.Add(this.labelRouteList);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table1[this.labelRouteList]));
			w28.TopAttach = ((uint)(3));
			w28.BottomAttach = ((uint)(4));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ydateDocument = new global::QS.Widgets.GtkUI.DatePicker();
			this.ydateDocument.Events = ((global::Gdk.EventMask)(256));
			this.ydateDocument.Name = "ydateDocument";
			this.ydateDocument.WithTime = false;
			this.ydateDocument.HideCalendarButton = false;
			this.ydateDocument.Date = new global::System.DateTime(0);
			this.ydateDocument.IsEditable = true;
			this.ydateDocument.AutoSeparation = true;
			this.table1.Add(this.ydateDocument);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table1[this.ydateDocument]));
			w29.TopAttach = ((uint)(1));
			w29.BottomAttach = ((uint)(2));
			w29.LeftAttach = ((uint)(3));
			w29.RightAttach = ((uint)(4));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.yEntryRouteList = new global::QS.Widgets.GtkUI.RepresentationEntry();
			this.yEntryRouteList.Events = ((global::Gdk.EventMask)(256));
			this.yEntryRouteList.Name = "yEntryRouteList";
			this.table1.Add(this.yEntryRouteList);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table1[this.yEntryRouteList]));
			w30.TopAttach = ((uint)(3));
			w30.BottomAttach = ((uint)(4));
			w30.LeftAttach = ((uint)(1));
			w30.RightAttach = ((uint)(2));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ylabelCashier = new global::Gamma.GtkWidgets.yLabel();
			this.ylabelCashier.Name = "ylabelCashier";
			this.ylabelCashier.Xalign = 0F;
			this.ylabelCashier.LabelProp = global::Mono.Unix.Catalog.GetString("Кассир");
			this.table1.Add(this.ylabelCashier);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table1[this.ylabelCashier]));
			w31.LeftAttach = ((uint)(3));
			w31.RightAttach = ((uint)(4));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add(this.table1);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.table1]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vboxDebts = new global::Gtk.VBox();
			this.vboxDebts.Name = "vboxDebts";
			this.vboxDebts.Spacing = 6;
			this.vboxDebts.BorderWidth = ((uint)(6));
			// Container child vboxDebts.Gtk.Box+BoxChild
			this.labelTableTitle = new global::Gtk.Label();
			this.labelTableTitle.Name = "labelTableTitle";
			this.labelTableTitle.Xalign = 0F;
			this.labelTableTitle.LabelProp = global::Mono.Unix.Catalog.GetString("Последние выданные авансы:");
			this.vboxDebts.Add(this.labelTableTitle);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vboxDebts[this.labelTableTitle]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vboxDebts.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.ytreeviewDebts = new global::Gamma.GtkWidgets.yTreeView();
			this.ytreeviewDebts.CanFocus = true;
			this.ytreeviewDebts.Name = "ytreeviewDebts";
			this.GtkScrolledWindow1.Add(this.ytreeviewDebts);
			this.vboxDebts.Add(this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vboxDebts[this.GtkScrolledWindow1]));
			w35.Position = 1;
			this.vbox1.Add(this.vboxDebts);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vboxDebts]));
			w36.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Основание:");
			this.vbox1.Add(this.label6);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label6]));
			w37.Position = 3;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ytextviewDescription = new global::Gamma.GtkWidgets.yTextView();
			this.ytextviewDescription.CanFocus = true;
			this.ytextviewDescription.Name = "ytextviewDescription";
			this.ytextviewDescription.WrapMode = ((global::Gtk.WrapMode)(3));
			this.GtkScrolledWindow.Add(this.ytextviewDescription);
			this.vbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
			w39.Position = 4;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.comboExpenseCategory.Hide();
			this.labelExpenseTitle.Hide();
			this.vboxDebts.Hide();
			this.Hide();
		}
	}
}
